name = "royalsync-api"
main = "worker/index.ts"
compatibility_date = "2026-09-05"
compatibility_flags = ["nodejs_compat"]

[vars]
CORS_ORIGINS = "*"
AUTH_SECRET = "supersecretjwtkey"
BOOTSTRAP_TOKEN = "bootstrap123"

[[d1_databases]]
binding = "DB"
database_name = "royalsync"
database_id = "1cd61de7-cdc0-475d-8754-5d16bc020e09"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "DOCS"
bucket_name = "royalsync-documents"

[env.production]
name = "royalsync-api-production"

[env.production.vars]
CORS_ORIGINS = "*"

[[env.production.d1_databases]]
binding = "DB"
database_name = "royalsync"
database_id = "1cd61de7-cdc0-475d-8754-5d16bc020e09"
migrations_dir = "migrations"

[[env.production.r2_buckets]]
binding = "DOCS"
bucket_name = "royalsync-documents"
