"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const cors_1 = __importDefault(require("cors"));
const dotenv_1 = __importDefault(require("dotenv"));
const AuthController_1 = require("./controllers/iam/AuthController");
const UserController_1 = require("./controllers/iam/UserController");
const ClientController_1 = require("./controllers/crm/ClientController");
const LeadController_1 = require("./controllers/crm/LeadController");
const PolicyController_1 = require("./controllers/policies/PolicyController");
const ClaimController_1 = require("./controllers/claims/ClaimController");
const TaskController_1 = require("./controllers/workflow/TaskController");
dotenv_1.default.config();
const app = (0, express_1.default)();
app.use((0, cors_1.default)());
app.use(express_1.default.json());
const auth = new AuthController_1.AuthController();
const users = new UserController_1.UserController();
const clients = new ClientController_1.ClientController();
const leads = new LeadController_1.LeadController();
const policies = new PolicyController_1.PolicyController();
const claims = new ClaimController_1.ClaimController();
const tasks = new TaskController_1.TaskController();
app.post('/api/auth/login', auth.login);
app.get('/api/iam/users', users.getUsers);
app.get('/api/crm/clients', clients.getClients);
app.post('/api/crm/clients', clients.createClient);
app.get('/api/crm/leads', leads.getLeads);
app.put('/api/crm/leads/:id/status', leads.updateLeadStatus);
app.get('/api/policies', policies.getPolicies);
app.get('/api/claims', claims.getClaims);
app.get('/api/workflow/tasks', tasks.getTasks);
app.put('/api/workflow/tasks/:id/toggle', tasks.toggleTask);
app.listen(5000, () => console.log('Server running on 5000'));
