// Client-side mirror of the backend merge engine (backend/src/lib/templateRender.ts),
// used only for the instant live preview in the template builder. The authoritative
// merge for generated PDFs runs on the server.

const escapeHtml = (v: unknown): string =>
  String(v ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

const resolvePath = (ctx: unknown, path: string): unknown =>
  path.split('.').reduce<unknown>((acc, key) => (acc && typeof acc === 'object' ? (acc as Record<string, unknown>)[key] : undefined), ctx);

const replaceScalars = (tpl: string, ctx: unknown): string =>
  tpl.replace(/\{\{\s*([\w.]+)\s*\}\}/g, (_m, path: string) => escapeHtml(resolvePath(ctx, path)));

export const renderMerge = (template: string, context: Record<string, unknown>): string => {
  const withLoops = template.replace(
    /\{\{\s*#each\s+([\w.]+)\s*\}\}([\s\S]*?)\{\{\s*\/each\s*\}\}/g,
    (_m, collectionPath: string, inner: string) => {
      const collection = resolvePath(context, collectionPath);
      if (!Array.isArray(collection)) return '';
      return collection.map((item) => replaceScalars(inner, { ...context, this: item })).join('');
    },
  );
  return replaceScalars(withLoops, context);
};

export const sampleContext = (company?: string): Record<string, unknown> => ({
  client: {
    firstName: 'Sipho', lastName: 'Nkosi', fullName: 'Sipho Nkosi',
    idNumber: '9001015009087', mobile: '082 555 1234', email: 'sipho@example.co.za',
    kycStatus: 'verified', riskProfile: 'Moderate',
  },
  adviser: { name: 'Thandi Mbeki' },
  company: company || 'Santam',
  broker: { name: 'Royal Square Financial' },
  date: { today: new Date().toLocaleDateString('en-ZA', { day: '2-digit', month: 'short', year: 'numeric' }), year: String(new Date().getFullYear()) },
  policies: [
    { policyNumber: 'SAN-2024-GG-1234567', type: 'Comprehensive Motor', premium: 'R 1,365.00', sumAssured: 'R 320,000.00', insurer: 'Santam' },
    { policyNumber: 'SAN-2024-HO-7654321', type: 'Home Contents', premium: 'R 540.00', sumAssured: 'R 180,000.00', insurer: 'Santam' },
  ],
  policy: { policyNumber: 'SAN-2024-GG-1234567', type: 'Comprehensive Motor', premium: 'R 1,365.00', sumAssured: 'R 320,000.00', insurer: 'Santam' },
});

// Wraps merged body in the same print-ready shell used server-side.
export const documentShell = (title: string, company: string, broker: string, bodyHtml: string): string => `<!doctype html><html><head><meta charset="utf-8"/>
<style>
  body { font-family: Georgia, 'Times New Roman', serif; color:#1f2933; font-size:13px; line-height:1.55; margin:0; padding:28px; }
  .rs-header{ display:flex; justify-content:space-between; align-items:flex-start; border-bottom:3px solid #c0392b; padding-bottom:12px; margin-bottom:22px; }
  .rs-header .brand{ font-family:Arial,sans-serif; font-weight:700; font-size:16px; color:#c0392b; letter-spacing:.5px; }
  .rs-header .company{ font-family:Arial,sans-serif; text-align:right; font-size:11px; color:#52606d; }
  .rs-title{ font-family:Arial,sans-serif; font-size:20px; font-weight:700; margin:0 0 18px; }
  h1,h2,h3{ font-family:Arial,sans-serif; }
  table{ width:100%; border-collapse:collapse; margin:12px 0; font-size:12px; }
  th,td{ border:1px solid #cbd2d9; padding:6px 9px; text-align:left; } th{ background:#f5f7fa; font-family:Arial,sans-serif; }
  ul,ol{ padding-left:20px; }
  .rs-footer{ margin-top:36px; padding-top:12px; border-top:1px solid #cbd2d9; font-family:Arial,sans-serif; font-size:10px; color:#7b8794; text-align:center; }
</style></head><body>
  <div class="rs-header"><div class="brand">${escapeHtml(broker || 'Royal Square Financial')}</div><div class="company">${company ? 'Prepared for ' + escapeHtml(company) : ''}</div></div>
  <div class="rs-title">${escapeHtml(title)}</div>
  <div>${bodyHtml}</div>
  <div class="rs-footer">Generated by RoyalSync${company ? ' · ' + escapeHtml(company) : ''} · This document is confidential and subject to FAIS &amp; POPIA.</div>
</body></html>`;
